AWSTemplateFormatVersion: 2010-09-09
Description: |
  ALperle yaptigimiz
Parameters:
  
Resources:
  Project101KittensCarouselStaticWebsiteEC2:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0022f774911c1d690
      InstanceType: t2.micro
      KeyName: firstkey
      SecurityGroups:
        - Project-101-kittens-carousel-static-website-ec2-SSH-HTTPS-HTTP-ALL
      Tags:
        - Key: Name
          Value: Project-101-kittens-carousel-static-website-ec2
        - Key: ProjectType
          Value: AWS Project
      UserData: 
        #! /bin/bash
        yum update -y
        yum install httpd -y
        cd /var/www/html
        FOLDER="https://raw.githubusercontent.com/denizoglu/AWS-Project-101-kittens-carousel-static-website-ec2/main/static-web/"
        wget ${FOLDER}index.html
        wget ${FOLDER}cat0.jpg
        wget ${FOLDER}cat1.jpg
        wget ${FOLDER}cat2.jpg
        wget ${FOLDER}cat3.png
        systemctl start httpd
        systemctl enable httpd
      Volumes:
        Volumes
Outputs: